import {
    ArrowLeft,
    ArrowRight,
    BadgeCheck,
    Bone,
    BookOpen,
    CalendarDays,
    Car,
    Check,
    ChevronRight,
    CirclePlay,
    Dog,
    Feather,
    Flame,
    GraduationCap,
    Heart,
    HeartPulse,
    House,
    MapPin,
    Mars,
    Menu,
    MessageCircle,
    PawPrint,
    Pencil,
    Plus,
    Quote,
    Scissors,
    Search,
    ShieldCheck,
    Sofa,
    Sparkles,
    Star,
    Stethoscope,
    Sun,
    Trash2,
    UserRound,
    Users,
    Venus,
    createIcons,
} from 'lucide';

const renderIcons = () => createIcons({
    icons: {
        ArrowLeft,
        ArrowRight,
        BadgeCheck,
        Bone,
        BookOpen,
        CalendarDays,
        Car,
        Check,
        ChevronRight,
        CirclePlay,
        Dog,
        Feather,
        Flame,
        GraduationCap,
        Heart,
        HeartPulse,
        House,
        MapPin,
        Mars,
        Menu,
        MessageCircle,
        PawPrint,
        Pencil,
        Plus,
        Quote,
        Scissors,
        Search,
        ShieldCheck,
        Sofa,
        Sparkles,
        Star,
        Stethoscope,
        Sun,
        Trash2,
        UserRound,
        Users,
        Venus,
    },
});

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderIcons);
} else {
    renderIcons();
}
